### ISSUE TITLE
Why GPLv3 for LLVM modifications? — and please switch to Apache 2.0 ;)

### ISSUE THREAD

**Issue by rothmichaels** [realtime-sanitizer/radsan#30]
Why are your modifications to LLVM licensed under GPLv3 vs Apache 2.0 like the rest of LLVM? 

It would be great to get this integrated into LLVM someday and I don't see them taking in LLVM changes under GPLv3 license. I imagine there might be some potential contributors who wouldn't want to mix up their other LLVM development with viral GPLv3 changes to LLVM.

One other thought, IANAL but I think this creates a complex licensing topic. While Apache 2.0 says other licenses can be used on modifications:

> You may add Your own copyright statement to Your modifications and may provide additional or different license terms and conditions for use, reproduction, or distribution of Your modifications, or for any such Derivative Works as a whole, provided Your use, reproduction, and distribution of the Work otherwise complies with the conditions stated in this License.

But Apache also says that GLPv3 and Apache 2.0 compatibility is only one way: you can include Apache 2.0 code in a GPLv3 project but not vice versa (I think this project is doing the later): https://www.apache.org/licenses/GPL-compatibility.html

**Comment by davidtrevelyan** [comment]
Hi @rothmichaels - thanks for the good question! The short answer doesn't really answer your question directly, but is probably what you're most interested in - we're in the process of integrating RADSan into LLVM, and as part of that process the license will of course be changed from GPLv3 to Apache 2.0 so that it matches with the LLVM project. 

The answer that directly answers your question "why is it GPLv3" is because, at the time of development, we didn't know whether RADSan would land in LLVM, and if it didn't, we didn't know how we wanted to license it. We knew we wanted it to be open source, but we didn't know the degree of freedom we wanted to grant everyone, so we wanted a license that felt like it postponed the decision as much as possible. GPLv3 seemed to fit the bill - it left us space to open up to something with fewer restrictions, whereas the other way around is not really possible - you can't convert MIT to GPL once it's out there!

**Comment by davidtrevelyan** [comment]
Closing because I believe there's no action to be taken here. @rothmichaels thanks for your interest and please let me know if there's anything else I can help answer on the licensing topic!
